/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DnsRecordService } from "../dnsRecord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DnsRecordCreateInput } from "./DnsRecordCreateInput";
import { DnsRecord } from "./DnsRecord";
import { DnsRecordFindManyArgs } from "./DnsRecordFindManyArgs";
import { DnsRecordWhereUniqueInput } from "./DnsRecordWhereUniqueInput";
import { DnsRecordUpdateInput } from "./DnsRecordUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DnsRecordControllerBase {
  constructor(
    protected readonly service: DnsRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DnsRecord })
  @nestAccessControl.UseRoles({
    resource: "DnsRecord",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDnsRecord(
    @common.Body() data: DnsRecordCreateInput
  ): Promise<DnsRecord> {
    return await this.service.createDnsRecord({
      data: {
        ...data,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        id: true,
        name: true,

        tenant: {
          select: {
            id: true,
          },
        },

        ttl: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DnsRecord] })
  @ApiNestedQuery(DnsRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DnsRecord",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dnsRecords(@common.Req() request: Request): Promise<DnsRecord[]> {
    const args = plainToClass(DnsRecordFindManyArgs, request.query);
    return this.service.dnsRecords({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        name: true,

        tenant: {
          select: {
            id: true,
          },
        },

        ttl: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DnsRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsRecord",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dnsRecord(
    @common.Param() params: DnsRecordWhereUniqueInput
  ): Promise<DnsRecord | null> {
    const result = await this.service.dnsRecord({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        name: true,

        tenant: {
          select: {
            id: true,
          },
        },

        ttl: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DnsRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsRecord",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDnsRecord(
    @common.Param() params: DnsRecordWhereUniqueInput,
    @common.Body() data: DnsRecordUpdateInput
  ): Promise<DnsRecord | null> {
    try {
      return await this.service.updateDnsRecord({
        where: params,
        data: {
          ...data,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          id: true,
          name: true,

          tenant: {
            select: {
              id: true,
            },
          },

          ttl: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DnsRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsRecord",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDnsRecord(
    @common.Param() params: DnsRecordWhereUniqueInput
  ): Promise<DnsRecord | null> {
    try {
      return await this.service.deleteDnsRecord({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          name: true,

          tenant: {
            select: {
              id: true,
            },
          },

          ttl: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
